<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PricesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prices')->insert(
            [
                [
                    'price_categories_id' => 1,
                    'name' => 'Consultație',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Consultație, plan de tratament și poze',
                    'price_currency_id' => 1,
                    'value' => '350',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Control postoperator/ Scos fire',
                    'price_currency_id' => 1,
                    'value' => '50',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Detartraj ultrasunete, periaj, fluorizare',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Detartraj ultrasunete rapel 6 luni',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Detartraj subgingival',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Detartraj subgingival cu anestezie',
                    'price_currency_id' => 1,
                    'value' => '500',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'AirFlow',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratament albire',
                    'price_currency_id' => 1,
                    'value' => '1000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratament albire laser',
                    'price_currency_id' => 1,
                    'value' => '1600',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratament albire endodontică',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratamentul hiperesteziei gel',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => 'Per arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament endodontic monoradiculari',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Obturație (plombă) provizorie',
                    'price_currency_id' => 1,
                    'value' => '80',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Obturație (plombă) de compozit superficială',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Obturație (plombă) de compozit medie',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Obturație (plombă) de compozit profundă',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Fațetă de compozit',
                    'price_currency_id' => 1,
                    'value' => '450',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Reconstrucție fizionomica dinte',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratament cu ICON',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 4,
                    'name' => 'Tratament cu ICON',
                    'price_currency_id' => 1,
                    'value' => '1000',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament endodontic monoradiculari',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament endodontic pluriradiculari',
                    'price_currency_id' => 1,
                    'value' => '600',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament endodontic molar de minte',
                    'price_currency_id' => 1,
                    'value' => '800',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Retratament endodontic monoradiculari',
                    'price_currency_id' => 1,
                    'value' => '500',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Retratament endodontic pluriradiculari',
                    'price_currency_id' => 1,
                    'value' => '700',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Retratament endodontic molar de minte',
                    'price_currency_id' => 1,
                    'value' => '950',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Reconstrucție coronară',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Pulpotomie monoradiculari',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Pulpotomie pluriradiculari',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Aplicare MTA',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Alungire coronară simplă',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => "Per dinte",
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Alungire coronara cu remodelare os',
                    'price_currency_id' => 1,
                    'value' => '350',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Bypass corp străin',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Îndepărtare corp străin',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Îndepărtare pivot radicular',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Drenaj endodontic monoradiculari',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Drenaj endodontic pluriradiculari',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție dinte monoradicular',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție dinte pluriradicular',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție dinte parodontic mobil',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție cu separație radiculară',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție dinte inclus/semiinclus',
                    'price_currency_id' => 1,
                    'value' => '600',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Extracție dinte inclus/semiinclus cu PRF',
                    'price_currency_id' => 1,
                    'value' => '900',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Premolarizare',
                    'price_currency_id' => 1,
                    'value' => '350',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Rezecție apicală cu dop MTA',
                    'price_currency_id' => 1,
                    'value' => '700',
                    'quantifier' => 'Per rădăcină',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Regularizare creastă alveolară',
                    'price_currency_id' => 1,
                    'value' => '350',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp închis SRP',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp închis SRP',
                    'price_currency_id' => 1,
                    'value' => '850',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp închis SRP',
                    'price_currency_id' => 1,
                    'value' => '1600',
                    'quantifier' => 'Arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp deschis',
                    'price_currency_id' => 1,
                    'value' => '450',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp deschis',
                    'price_currency_id' => 1,
                    'value' => '1900',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Chiuretaj în camp deschis',
                    'price_currency_id' => 1,
                    'value' => '3500',
                    'quantifier' => 'Arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Acoperire retracție gingivală simplă',
                    'price_currency_id' => 1,
                    'value' => '1000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Acoperire retracții gingivale multiple',
                    'price_currency_id' => 1,
                    'value' => '2300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Dezinfecție laser',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Prelevare țesut conjunctiv',
                    'price_currency_id' => 1,
                    'value' => '900',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Imobilizare dinți parodontici',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Injectare PRP',
                    'price_currency_id' => 1,
                    'value' => '600',
                    'quantifier' => 'Per arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Injectare PRP',
                    'price_currency_id' => 1,
                    'value' => '1100',
                    'quantifier' => 'Ambele arcade',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană provizorie de compozit',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => 'Realizată în cabinet',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană provizorie PMMA',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => 'Realizată în laborator',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Ablație element protetic',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană metalo-ceramică total fizionomică',
                    'price_currency_id' => 1,
                    'value' => '900',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană integral ceramică',
                    'price_currency_id' => 1,
                    'value' => '1900',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană ceramică pe suport de zirconiu',
                    'price_currency_id' => 1,
                    'value' => '1600',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană BIOHPP',
                    'price_currency_id' => 1,
                    'value' => '1400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană fizionomică pe capă de titan',
                    'price_currency_id' => 1,
                    'value' => '1400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Punte Marryland',
                    'price_currency_id' => 1,
                    'value' => '800',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Fațetă ceramică',
                    'price_currency_id' => 1,
                    'value' => '2000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Proteză totală acrilică ranforsată',
                    'price_currency_id' => 1,
                    'value' => '2200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Proteză parțială acrilică',
                    'price_currency_id' => 1,
                    'value' => '1800',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Proteză flexibilă',
                    'price_currency_id' => 1,
                    'value' => '2500',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Proteză parțială scheletată',
                    'price_currency_id' => 1,
                    'value' => '3200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Proteză parțială scheletată specială',
                    'price_currency_id' => 1,
                    'value' => '3800',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Rebazare / reparație proteză',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Kemmeny',
                    'price_currency_id' => 1,
                    'value' => '450',
                    'quantifier' => 'Până la 4 dinți',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Gutieră',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => 'Albire, bruxism, contenție',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Model de studiu',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Wax-up',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Mock-up',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Cimentare coroană',
                    'price_currency_id' => 1,
                    'value' => '80',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană provizorie PMMA pe implant',
                    'price_currency_id' => 1,
                    'value' => '1000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Înșerare implant Megagen AnyRidge',
                    'price_currency_id' => 1,
                    'value' => '3200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 3,
                    'name' => 'Coroană metalo-ceramică pe implant',
                    'price_currency_id' => 1,
                    'value' => '2000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Manoperă Sinus lift direct',
                    'price_currency_id' => 1,
                    'value' => '3000',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Decapusonare implant',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Decapusonare implant cu laser',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Consultație pedodonție',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Vizită de acomodare',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Periaj profesional',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Fluorizare cu geluri',
                    'price_currency_id' => 1,
                    'value' => '80',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 2,
                    'name' => 'Sigilare fisuri compozit',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Obturație dinți deciduali (de lapte) compozit',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Obturație dinți deciduali (de lapte) Glassionomer',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Extracție dinte decidual (de lapte) cu resorbție',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Extracție dinte decidual (de lapte) fără resorbție',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Pansament Ca-OH',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Pansament devitalizant',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Drenaj endodontic',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Incizie și drenaj abces',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament Gangrenă',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Tratament de urgență',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Pulpotomie dinte decidual (de lapte)',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Control tratamente laser 3 / 6 luni',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Gingivectomie laser simplă',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Gingivectomie',
                    'price_currency_id' => 1,
                    'value' => '600',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Gingivectomie',
                    'price_currency_id' => 1,
                    'value' => '1100',
                    'quantifier' => 'Arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Gingivectomie și osteotomie',
                    'price_currency_id' => 1,
                    'value' => '1400',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Gingivoplastie',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Alungire coronară',
                    'price_currency_id' => 1,
                    'value' => '250',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Alungire coronară cu remodelare os',
                    'price_currency_id' => 1,
                    'value' => '450',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Chiuretaj câmp închis SRP laser',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Chiuretaj câmp închis SRP laser',
                    'price_currency_id' => 1,
                    'value' => '1000',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Chiuretaj câmp închis SRP laser',
                    'price_currency_id' => 1,
                    'value' => '1600',
                    'quantifier' => 'Arcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Dezinfecție laser',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Frenectomie labială laser',
                    'price_currency_id' => 1,
                    'value' => '350',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Indepartare bridă',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Vestibuloplastie',
                    'price_currency_id' => 1,
                    'value' => '800',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Regularizare creasta balanta',
                    'price_currency_id' => 1,
                    'value' => '700',
                    'quantifier' => 'Hemiarcadă',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 10,
                    'name' => 'Decapusonare',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Tratamentul pericoronaritei',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 6,
                    'name' => 'Incizie și dezinfecție abces',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Descoperire de implant simplă',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Descoperire de implant subosos',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Descoperire dinte inclus submucos',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 9,
                    'name' => 'Descoperire dinte inclus subosos',
                    'price_currency_id' => 1,
                    'value' => '400',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Ulcer aftos (afte bucale)',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Depigmentare gingivala',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Îndepărtare pată vasculară',
                    'price_currency_id' => 1,
                    'value' => '300',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Tratamentul hiperesteziei',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Terapia durerii',
                    'price_currency_id' => 1,
                    'value' => '150',
                    'quantifier' => 'Per ședință',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 1,
                    'name' => 'Terapia durerii',
                    'price_currency_id' => 1,
                    'value' => '600',
                    'quantifier' => '6 ședințe',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 7,
                    'name' => 'Biostimulare după activare ortodontică',
                    'price_currency_id' => 1,
                    'value' => '50',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Biostimulare',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 8,
                    'name' => 'Evicțiune gingivală',
                    'price_currency_id' => 1,
                    'value' => '100',
                    'quantifier' => 'Per dinte',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Periimplantită',
                    'price_currency_id' => 1,
                    'value' => '450',
                    'quantifier' => 'Per ședință',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
                [
                    'price_categories_id' => 5,
                    'name' => 'Desensibilizare ambele arcade',
                    'price_currency_id' => 1,
                    'value' => '200',
                    'quantifier' => 'Per ședință',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ],
            ]);
    }
}
